security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true
            access_denied_handler: App\Security\AccessDeniedHandler

    access_control:
        - { path: ^/$, roles: 'ROLE_USER'}
        - { path: ^/login$, allow_if: "not has_role('ROLE_USER')" }
        - { path: ^/register, allow_if: "not has_role('ROLE_USER')" }