version: '3'

services:
  nginx:
    image: nginx:1.11-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php

  php:
    image: jorge07/alpine-php:7.2-dev-sf
    ports:
      - "2323:22"
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'test_mintos'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'toor'
    volumes:
      - db_data:/var/lib/mysql

volumes:
    db_data: